export type TStudents = {
  id: string;
  first_name: string;
  last_name: string;
  middle_name?: string;
  gender: "male" | "female" | "other";
  nationality: string;
  dob: string;
  phone_number: string;
  email_address: string;
  address: string;

  guardian_name: string;
  guardian_occupation: string;
  guardian_phone_number: string;
  guardian_relation: string;
  guardian_email: string;

  grade: string;
  section: string;
  status: "active" | "inactive" | "pending" | "graduated";
};

export type TTeachers = {
  id: string;
  name: string;
  status: "active" | "inactive";
  subject: string;
  email: string;
};

export interface TClasses {
  id: string;
  class: string;
  section: string;
  teacher: string;
  studentsEnrolled: number;
  room: string;
  academicYear: string;
}

export type TAdmission = {
  applicationId: string;
  name: string;
  gradeLevel: string;
  dateApplied: string;
  status:
    | "active"
    | "inactive"
    | "Pending"
    | "Approved"
    | "Rejected"
    | "Waitlisted";

  email: string;
};

export async function getStudents(): Promise<TStudents[]> {
  return [
    {
      id: "s001",
      first_name: "Juan",
      last_name: "Dela Cruz",
      middle_name: "Santos",
      gender: "male",
      nationality: "Filipino",
      dob: "2006-05-14",
      phone_number: "09171234567",
      email_address: "juan.delacruz@example.com",
      address: "123 Mabini St, Manila",
      guardian_name: "Maria Dela Cruz",
      guardian_occupation: "Teacher",
      guardian_phone_number: "09181234567",
      guardian_relation: "Mother",
      guardian_email: "maria.delacruz@example.com",
      grade: "10",
      section: "A",
      status: "active",
    },
    {
      id: "s002",
      first_name: "Ana",
      last_name: "Reyes",
      middle_name: "Lopez",
      gender: "female",
      nationality: "Filipino",
      dob: "2007-01-22",
      phone_number: "09174567890",
      email_address: "ana.reyes@example.com",
      address: "45 Katipunan Ave, Quezon City",
      guardian_name: "Jose Reyes",
      guardian_occupation: "Engineer",
      guardian_phone_number: "09183456789",
      guardian_relation: "Father",
      guardian_email: "jose.reyes@example.com",
      grade: "9",
      section: "B",
      status: "active",
    },
    {
      id: "s003",
      first_name: "Michael",
      last_name: "Smith",
      middle_name: "Allen",
      gender: "male",
      nationality: "American",
      dob: "2005-11-30",
      phone_number: "09991234567",
      email_address: "michael.smith@example.com",
      address: "Greenhills, San Juan",
      guardian_name: "Karen Smith",
      guardian_occupation: "Nurse",
      guardian_phone_number: "09186789012",
      guardian_relation: "Mother",
      guardian_email: "karen.smith@example.com",
      grade: "11",
      section: "C",
      status: "active",
    },
    {
      id: "s004",
      first_name: "Sophia",
      last_name: "Garcia",
      middle_name: "Martinez",
      gender: "female",
      nationality: "Filipino",
      dob: "2008-03-18",
      phone_number: "09175678901",
      email_address: "sophia.garcia@example.com",
      address: "Cebu City, Cebu",
      guardian_name: "Carlos Garcia",
      guardian_occupation: "Businessman",
      guardian_phone_number: "09184567891",
      guardian_relation: "Father",
      guardian_email: "carlos.garcia@example.com",
      grade: "8",
      section: "D",
      status: "pending",
    },
    {
      id: "s005",
      first_name: "Ethan",
      last_name: "Tan",
      middle_name: "Lim",
      gender: "male",
      nationality: "Chinese-Filipino",
      dob: "2006-09-09",
      phone_number: "09172345678",
      email_address: "ethan.tan@example.com",
      address: "Binondo, Manila",
      guardian_name: "Michelle Tan",
      guardian_occupation: "Entrepreneur",
      guardian_phone_number: "09183456701",
      guardian_relation: "Mother",
      guardian_email: "michelle.tan@example.com",
      grade: "10",
      section: "B",
      status: "active",
    },
    {
      id: "s006",
      first_name: "Grace",
      last_name: "Villanueva",
      middle_name: "Torres",
      gender: "female",
      nationality: "Filipino",
      dob: "2005-07-12",
      phone_number: "09181239876",
      email_address: "grace.villanueva@example.com",
      address: "Makati City, NCR",
      guardian_name: "Ramon Villanueva",
      guardian_occupation: "Lawyer",
      guardian_phone_number: "09184561234",
      guardian_relation: "Father",
      guardian_email: "ramon.villanueva@example.com",
      grade: "11",
      section: "A",
      status: "active",
    },
    {
      id: "s007",
      first_name: "David",
      last_name: "Chavez",
      middle_name: "Fernandez",
      gender: "male",
      nationality: "Filipino",
      dob: "2007-02-28",
      phone_number: "09173450987",
      email_address: "david.chavez@example.com",
      address: "Davao City, Davao del Sur",
      guardian_name: "Elena Chavez",
      guardian_occupation: "Doctor",
      guardian_phone_number: "09182345678",
      guardian_relation: "Mother",
      guardian_email: "elena.chavez@example.com",
      grade: "9",
      section: "A",
      status: "inactive",
    },
    {
      id: "s008",
      first_name: "Liam",
      last_name: "Johnson",
      middle_name: "Ray",
      gender: "male",
      nationality: "Canadian",
      dob: "2004-12-25",
      phone_number: "09983456712",
      email_address: "liam.johnson@example.com",
      address: "Pasig City, NCR",
      guardian_name: "Sarah Johnson",
      guardian_occupation: "Architect",
      guardian_phone_number: "09183456745",
      guardian_relation: "Mother",
      guardian_email: "sarah.johnson@example.com",
      grade: "12",
      section: "C",
      status: "graduated",
    },
    {
      id: "s009",
      first_name: "Isabella",
      last_name: "Lopez",
      middle_name: "Ramos",
      gender: "female",
      nationality: "Filipino",
      dob: "2008-06-10",
      phone_number: "09175671234",
      email_address: "isabella.lopez@example.com",
      address: "Iloilo City, Iloilo",
      guardian_name: "Antonio Lopez",
      guardian_occupation: "Farmer",
      guardian_phone_number: "09183450123",
      guardian_relation: "Father",
      guardian_email: "antonio.lopez@example.com",
      grade: "8",
      section: "B",
      status: "pending",
    },
    {
      id: "s010",
      first_name: "Noah",
      last_name: "Santos",
      middle_name: "Rivera",
      gender: "male",
      nationality: "Filipino",
      dob: "2006-10-01",
      phone_number: "09183458901",
      email_address: "noah.santos@example.com",
      address: "Taguig City, NCR",
      guardian_name: "Carmen Santos",
      guardian_occupation: "Accountant",
      guardian_phone_number: "09184569012",
      guardian_relation: "Mother",
      guardian_email: "carmen.santos@example.com",
      grade: "10",
      section: "C",
      status: "active",
    },
    // 👇 add more until 20
    {
      id: "s011",
      first_name: "Chloe",
      last_name: "Nguyen",
      middle_name: "Tran",
      gender: "female",
      nationality: "Vietnamese",
      dob: "2005-04-20",
      phone_number: "09981234567",
      email_address: "chloe.nguyen@example.com",
      address: "Mandaluyong City, NCR",
      guardian_name: "Minh Nguyen",
      guardian_occupation: "Businessman",
      guardian_phone_number: "09184567890",
      guardian_relation: "Father",
      guardian_email: "minh.nguyen@example.com",
      grade: "11",
      section: "B",
      status: "active",
    },
    {
      id: "s012",
      first_name: "Gabriel",
      last_name: "Perez",
      middle_name: "Domingo",
      gender: "male",
      nationality: "Filipino",
      dob: "2007-08-15",
      phone_number: "09182349876",
      email_address: "gabriel.perez@example.com",
      address: "Baguio City, Benguet",
      guardian_name: "Rosa Perez",
      guardian_occupation: "Teacher",
      guardian_phone_number: "09184561239",
      guardian_relation: "Mother",
      guardian_email: "rosa.perez@example.com",
      grade: "9",
      section: "C",
      status: "active",
    },
    {
      id: "s013",
      first_name: "Olivia",
      last_name: "Torres",
      middle_name: "Navarro",
      gender: "female",
      nationality: "Filipino",
      dob: "2006-11-11",
      phone_number: "09185671234",
      email_address: "olivia.torres@example.com",
      address: "Legazpi City, Albay",
      guardian_name: "Miguel Torres",
      guardian_occupation: "Engineer",
      guardian_phone_number: "09183457812",
      guardian_relation: "Father",
      guardian_email: "miguel.torres@example.com",
      grade: "10",
      section: "D",
      status: "active",
    },
    {
      id: "s014",
      first_name: "Lucas",
      last_name: "Morales",
      middle_name: "Diaz",
      gender: "male",
      nationality: "Filipino",
      dob: "2005-02-02",
      phone_number: "09186781234",
      email_address: "lucas.morales@example.com",
      address: "Caloocan City, NCR",
      guardian_name: "Teresa Morales",
      guardian_occupation: "Nurse",
      guardian_phone_number: "09182347890",
      guardian_relation: "Mother",
      guardian_email: "teresa.morales@example.com",
      grade: "11",
      section: "C",
      status: "inactive",
    },
    {
      id: "s015",
      first_name: "Mia",
      last_name: "Cruz",
      middle_name: "Flores",
      gender: "female",
      nationality: "Filipino",
      dob: "2008-09-19",
      phone_number: "09183451234",
      email_address: "mia.cruz@example.com",
      address: "Bacolod City, Negros Occidental",
      guardian_name: "Jose Cruz",
      guardian_occupation: "Driver",
      guardian_phone_number: "09184567891",
      guardian_relation: "Father",
      guardian_email: "jose.cruz@example.com",
      grade: "8",
      section: "A",
      status: "pending",
    },
    {
      id: "s016",
      first_name: "Alexander",
      last_name: "Go",
      middle_name: "Sy",
      gender: "male",
      nationality: "Chinese-Filipino",
      dob: "2006-06-06",
      phone_number: "09183457689",
      email_address: "alexander.go@example.com",
      address: "Quezon City, NCR",
      guardian_name: "Robert Go",
      guardian_occupation: "Entrepreneur",
      guardian_phone_number: "09181234589",
      guardian_relation: "Father",
      guardian_email: "robert.go@example.com",
      grade: "10",
      section: "B",
      status: "active",
    },
    {
      id: "s017",
      first_name: "Zoe",
      last_name: "Castro",
      middle_name: "Mendoza",
      gender: "female",
      nationality: "Filipino",
      dob: "2007-07-21",
      phone_number: "09182340987",
      email_address: "zoe.castro@example.com",
      address: "Antipolo City, Rizal",
      guardian_name: "Angela Castro",
      guardian_occupation: "Accountant",
      guardian_phone_number: "09184560123",
      guardian_relation: "Mother",
      guardian_email: "angela.castro@example.com",
      grade: "9",
      section: "D",
      status: "active",
    },
    {
      id: "s018",
      first_name: "Daniel",
      last_name: "Lim",
      middle_name: "Ong",
      gender: "male",
      nationality: "Filipino",
      dob: "2005-05-17",
      phone_number: "09181236789",
      email_address: "daniel.lim@example.com",
      address: "Valenzuela City, NCR",
      guardian_name: "Cynthia Lim",
      guardian_occupation: "Nurse",
      guardian_phone_number: "09184567812",
      guardian_relation: "Mother",
      guardian_email: "cynthia.lim@example.com",
      grade: "11",
      section: "D",
      status: "active",
    },
    {
      id: "s019",
      first_name: "Emily",
      last_name: "Ramos",
      middle_name: "Salazar",
      gender: "female",
      nationality: "Filipino",
      dob: "2006-01-30",
      phone_number: "09183459012",
      email_address: "emily.ramos@example.com",
      address: "General Santos City, South Cotabato",
      guardian_name: "Pedro Ramos",
      guardian_occupation: "Farmer",
      guardian_phone_number: "09182349012",
      guardian_relation: "Father",
      guardian_email: "pedro.ramos@example.com",
      grade: "10",
      section: "C",
      status: "active",
    },
    {
      id: "s020",
      first_name: "Ryan",
      last_name: "Fernandez",
      middle_name: "Gomez",
      gender: "male",
      nationality: "Filipino",
      dob: "2007-12-12",
      phone_number: "09185670123",
      email_address: "ryan.fernandez@example.com",
      address: "Cavite City, Cavite",
      guardian_name: "Laura Fernandez",
      guardian_occupation: "Clerk",
      guardian_phone_number: "09184560987",
      guardian_relation: "Mother",
      guardian_email: "laura.fernandez@example.com",
      grade: "9",
      section: "B",
      status: "inactive",
    },
  ];
}

export async function getTeachers(): Promise<TTeachers[]> {
  return [
    {
      id: "t01",
      name: "Maria Santos",
      subject: "Mathematics",
      email: "maria.santos@example.com",
      status: "active",
    },
    {
      id: "t02",
      name: "Jose Ramirez",
      subject: "English",
      email: "jose.ramirez@example.com",
      status: "active",
    },
    {
      id: "t03",
      name: "Carmela Dela Cruz",
      subject: "Science",
      email: "carmela.delacruz@example.com",
      status: "inactive",
    },
    {
      id: "t04",
      name: "Ramon Villanueva",
      subject: "History",
      email: "ramon.villanueva@example.com",
      status: "active",
    },
    {
      id: "t05",
      name: "Angela Bautista",
      subject: "Computer Science",
      email: "angela.bautista@example.com",
      status: "active",
    },
    {
      id: "t06",
      name: "Francisco Tan",
      subject: "Physical Education",
      email: "francisco.tan@example.com",
      status: "active",
    },
    {
      id: "t07",
      name: "Melissa Ong",
      subject: "Filipino",
      email: "melissa.ong@example.com",
      status: "active",
    },
    {
      id: "t08",
      name: "Roberto Chua",
      subject: "Economics",
      email: "roberto.chua@example.com",
      status: "inactive",
    },
    {
      id: "t09",
      name: "Janine Flores",
      subject: "Biology",
      email: "janine.flores@example.com",
      status: "active",
    },
    {
      id: "t10",
      name: "Patrick Sy",
      subject: "Chemistry",
      email: "patrick.sy@example.com",
      status: "active",
    },
    {
      id: "t11",
      name: "Veronica Aquino",
      subject: "Arts",
      email: "veronica.aquino@example.com",
      status: "active",
    },
    {
      id: "t12",
      name: "Anthony Reyes",
      subject: "Physics",
      email: "anthony.reyes@example.com",
      status: "active",
    },
    {
      id: "t13",
      name: "Cynthia Lee",
      subject: "Music",
      email: "cynthia.lee@example.com",
      status: "active",
    },
    {
      id: "t14",
      name: "Mark Cruz",
      subject: "Geography",
      email: "mark.cruz@example.com",
      status: "active",
    },
    {
      id: "t15",
      name: "Sophia Mendoza",
      subject: "Literature",
      email: "sophia.mendoza@example.com",
      status: "active",
    },
  ];
}

export async function getClasses(): Promise<TClasses[]> {
  return [
    {
      id: "c01",
      class: "Grade 10",
      section: "Section A",
      teacher: "Maria Santos",
      studentsEnrolled: 35,
      room: "101",
      academicYear: "2025–2026",
    },
    {
      id: "c02",
      class: "Grade 10",
      section: "Section B",
      teacher: "Carmela Dela Cruz",
      studentsEnrolled: 32,
      room: "102",
      academicYear: "2025–2026",
    },
    {
      id: "c03",
      class: "Grade 11",
      section: "Section A",
      teacher: "Jose Ramirez",
      studentsEnrolled: 28,
      room: "201",
      academicYear: "2025–2026",
    },
    {
      id: "c04",
      class: "Grade 11",
      section: "Section B",
      teacher: "Ramon Villanueva",
      studentsEnrolled: 30,
      room: "202",
      academicYear: "2025–2026",
    },
    {
      id: "c05",
      class: "Grade 12",
      section: "Section A",
      teacher: "Anthony Reyes",
      studentsEnrolled: 27,
      room: "301",
      academicYear: "2025–2026",
    },
    {
      id: "c06",
      class: "Grade 12",
      section: "Section B",
      teacher: "Patrick Sy",
      studentsEnrolled: 29,
      room: "302",
      academicYear: "2025–2026",
    },
    {
      id: "c07",
      class: "Grade 9",
      section: "Section A",
      teacher: "Angela Bautista",
      studentsEnrolled: 36,
      room: "103",
      academicYear: "2025–2026",
    },
    {
      id: "c08",
      class: "Grade 9",
      section: "Section B",
      teacher: "Janine Flores",
      studentsEnrolled: 34,
      room: "104",
      academicYear: "2025–2026",
    },
    {
      id: "c09",
      class: "Grade 8",
      section: "Section A",
      teacher: "Melissa Ong",
      studentsEnrolled: 33,
      room: "105",
      academicYear: "2025–2026",
    },
    {
      id: "c10",
      class: "Grade 8",
      section: "Section B",
      teacher: "Roberto Chua",
      studentsEnrolled: 31,
      room: "106",
      academicYear: "2025–2026",
    },
    {
      id: "c11",
      class: "Grade 7",
      section: "Section A",
      teacher: "Veronica Aquino",
      studentsEnrolled: 37,
      room: "107",
      academicYear: "2025–2026",
    },
    {
      id: "c12",
      class: "Grade 7",
      section: "Section B",
      teacher: "Cynthia Lee",
      studentsEnrolled: 35,
      room: "108",
      academicYear: "2025–2026",
    },
    {
      id: "c13",
      class: "Grade 11",
      section: "Section C",
      teacher: "Mark Cruz",
      studentsEnrolled: 26,
      room: "203",
      academicYear: "2025–2026",
    },
    {
      id: "c14",
      class: "Grade 12",
      section: "Section C",
      teacher: "Sophia Mendoza",
      studentsEnrolled: 25,
      room: "303",
      academicYear: "2025–2026",
    },
  ];
}

export async function getAdmission(): Promise<TAdmission[]> {
  // Fetch data from your API here.
  return [
    {
      applicationId: "A-001",
      name: "Juan Dela Cruz",
      gradeLevel: "Grade 10",
      email: "juan.dc@example.com",
      status: "Pending",
      dateApplied: "2025-08-01",
    },
    {
      applicationId: "A-002",
      name: "Maria Santos",
      gradeLevel: "Grade 11 - STEM",
      email: "maria.santos@example.com",
      status: "Approved",
      dateApplied: "2025-08-02",
    },
    {
      applicationId: "A-003",
      name: "Jose Ramirez",
      gradeLevel: "Grade 12 - HUMSS",
      email: "jose.ramirez@example.com",
      status: "Rejected",
      dateApplied: "2025-08-02",
    },
    {
      applicationId: "A-004",
      name: "Carmela Dela Cruz",
      gradeLevel: "Grade 9",
      email: "carmela.dc@example.com",
      status: "Pending",
      dateApplied: "2025-08-03",
    },
    {
      applicationId: "A-005",
      name: "Mark Cruz",
      gradeLevel: "Grade 11 - ABM",
      email: "mark.cruz@example.com",
      status: "Waitlisted",
      dateApplied: "2025-08-03",
    },
    {
      applicationId: "A-006",
      name: "Angela Bautista",
      gradeLevel: "Grade 8",
      email: "angela.b@example.com",
      status: "Approved",
      dateApplied: "2025-08-04",
    },
    {
      applicationId: "A-007",
      name: "Roberto Chua",
      gradeLevel: "Grade 12 - STEM",
      email: "roberto.chua@example.com",
      status: "Pending",
      dateApplied: "2025-08-05",
    },
    {
      applicationId: "A-008",
      name: "Sophia Mendoza",
      gradeLevel: "Grade 11 - HUMSS",
      email: "sophia.mendoza@example.com",
      status: "Rejected",
      dateApplied: "2025-08-06",
    },
    {
      applicationId: "A-009",
      name: "Anthony Reyes",
      gradeLevel: "Grade 10",
      email: "anthony.reyes@example.com",
      status: "Pending",
      dateApplied: "2025-08-06",
    },
    {
      applicationId: "A-010",
      name: "Veronica Aquino",
      gradeLevel: "Grade 9",
      email: "veronica.aquino@example.com",
      status: "Approved",
      dateApplied: "2025-08-07",
    },
    {
      applicationId: "A-011",
      name: "Melissa Ong",
      gradeLevel: "Grade 8",
      email: "melissa.ong@example.com",
      status: "Pending",
      dateApplied: "2025-08-08",
    },
    {
      applicationId: "A-012",
      name: "Janine Flores",
      gradeLevel: "Grade 12 - ABM",
      email: "janine.flores@example.com",
      status: "Approved",
      dateApplied: "2025-08-08",
    },
    {
      applicationId: "A-013",
      name: "Patrick Sy",
      gradeLevel: "Grade 11 - STEM",
      email: "patrick.sy@example.com",
      status: "Waitlisted",
      dateApplied: "2025-08-09",
    },
    {
      applicationId: "A-014",
      name: "Ramon Villanueva",
      gradeLevel: "Grade 10",
      email: "ramon.v@example.com",
      status: "Rejected",
      dateApplied: "2025-08-10",
    },
    {
      applicationId: "A-015",
      name: "Cynthia Lee",
      gradeLevel: "Grade 9",
      email: "cynthia.lee@example.com",
      status: "Pending",
      dateApplied: "2025-08-11",
    },
    {
      applicationId: "A-016",
      name: "Mark Villena",
      gradeLevel: "Grade 8",
      email: "mark.villena@example.com",
      status: "Approved",
      dateApplied: "2025-08-11",
    },
    {
      applicationId: "A-017",
      name: "Clarisse Gomez",
      gradeLevel: "Grade 12 - HUMSS",
      email: "clarisse.gomez@example.com",
      status: "Pending",
      dateApplied: "2025-08-12",
    },
    {
      applicationId: "A-018",
      name: "Christian Dizon",
      gradeLevel: "Grade 11 - ABM",
      email: "christian.dizon@example.com",
      status: "Approved",
      dateApplied: "2025-08-12",
    },
    {
      applicationId: "A-019",
      name: "Gabrielle Tan",
      gradeLevel: "Grade 9",
      email: "gabrielle.tan@example.com",
      status: "Rejected",
      dateApplied: "2025-08-13",
    },
    {
      applicationId: "A-020",
      name: "Ethan Lim",
      gradeLevel: "Grade 10",
      email: "ethan.lim@example.com",
      status: "Pending",
      dateApplied: "2025-08-14",
    },
  ];
}
